# Generated by Django 2.2 on 2021-03-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210320_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/blog/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
