# Generated by Django 2.2 on 2021-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Заголовок'),
        ),
    ]
